### PR TITLE
Bugfix/git prompt

### PR DESCRIPTION
**Pull request by ollieshmollie**
I've noticed that most of my pairing partners who use macs aren't using a git-aware prompt. Asking around, many of them followed the instructions on your website. I'm convinced that the script is broken.

I've determined that the __git_ps1 variable needs to be escaped when inside double quotes. To test this, I exported your PS1 in my own bash profile, knowing that my git-prompt.sh lives in /usr/local/etc/bash-completion.d. Lo and behold, the branch name is nowhere to be found. Escaping the variable with a backslash, however, immediately solved the problem.

But there's a larger issue here. I recruited some of my cohort-mates to test my hypothesis (which is correct), and the backslash didn't fix the issue. I didn't have the wherewithal at the time to ask them to check the proper directories for the git-prompt.sh file, but I'm convinced that for some reason Homebrew never installed the git-completion.sh file in the bash-completion directory, forever dooming them to a miserable time without a git-aware prompt.

This could be solved in any number of ways, my favorite being adding an elif clause to install git-prompt.sh to the home directory. It could look something like this:
``` bash
git_prompt_script=/usr/local/etc/bash_completion.d/git-prompt.sh
# git-prompt lives in bash-completion
if [[ -s $git_prompt_script ]]; then
  source $git_prompt_script
  export GIT_PS1_SHOWDIRTYSTATE=1
  export PS1="\n$ColorRed\W$ColorReset$ColorGreen\$(__git_ps1)$ColorReset :> "

# git-prompt lives in home dir
elif [[ -s ~/.git-prompt.sh ]]; then
  source ~/.git-prompt.sh
  export GIT_PS1_SHOWDIRTYSTATE=1
  export PS1="\n$ColorRed\W$ColorReset$ColorGreen\$(__git_ps1)$ColorReset :> "

# otherwise, install it for them
else
  curl -s https://raw.githubusercontent.com/git/git/master/contrib/completion/git-prompt.sh > ~/.git-prompt.sh
  source ~/.git-prompt.sh
  export GIT_PS1_SHOWDIRTYSTATE=1
  export PS1="\n$ColorRed\W$ColorReset$ColorGreen\$(__git_ps1)$ColorReset :> "
fi
```
But there might be any number of reasons you wouldn't want to implement this, so I've just taken the liberty of editing the README to remind us (I know you asked to `brew install git`, but I feel this reinforces the notion) to upgrade all our Homebrew installed packages.

### CODE REVIEW

**Comment by ollieshmollie** [comment]
@sgharms 
btw loved your video on the history of UNIX, fascinating stuff

**Comment by ollieshmollie** [comment]
As I suspected, the solution may not be so simple. Four out of six students with whom I tried the solution weren't getting the expected result. It seems to be students that have installed a dev environment before coming to DBC are having trouble, and I can't tell whether it's an issue with HomeBrew not correctly installing the bash_completion directory, a $PATH issue, or some other variable that I haven't thought of.

**Comment by sgharms** [comment]
@ollieshmollie thanks for the video love. It's one of my favorite topics. 

I'll not pretend to have understood all this shell-fu at a glance esp. given that these were Topher's curated, collected, Topherized dot-files. It seems you want to do more debugging here?

**Comment by ollieshmollie** [comment]
@sgharms I'm trying, but it's extremely difficult with so many variables at play. The main fix is definitely to escape the __git_ps1 variable when inside double quotes. There's actually [another](https://github.com/Devbootcamp/dotfiles/pull/2) pull request I didn't see at first that addresses and "solves" the issue the same way, though it was never merged. But there must be a larger issue at work here because only two of out of the six people I tried it with showed the expected results.

Feel free to ignore the if elif else chain I wrote there, I tried it with one of my cohort mates and something about either having two git-prompt.sh files installed or possibly sublime changing tab indentation is messing with the git-prompt script itself. All in all it'll be impossible for me to truly debug this until I clean install my computer (or figure out a way to fake it) and install the DBC suite myself, which at this point is something I'm not prepared to do.

That said, I have a strong hunch that Homebrew is at the root of the problem, and will certainly continue experimenting. Homebrew installs and links the files in /usr/local/etc/bash_completion.d, and if those links are broken that could explain why the script isn't doing what it's supposed to do.

But hey, it's funny that you mention Topher's repo. Maybe the best solution is just to pull down his latest and use that! It looks like his latest bash profile doesn't even use git-prompt.sh, and instead opts for a custom function. That's a shame, though, because git-prompt has some great features (automatic remote comparison? uh yes please)

I'm going to get to the bottom of this. Thanks for getting back to me, and if you have any light to shed on some these concepts it would be greatly appreciated. I think it's important that new DBC students have a chance to have fun with and explore git, and git is definitely not fun when you're constantly having to type `git status` and `git branch` just to remember where you are.

**Comment by ollieshmollie** [comment]
@sgharms Added a setup script that I think will solve the problem, which I'm sure now is just the Homebrew install of git not being linked properly on some people's machines. You guys seemed to try to account for this by asking us to `brew install git` but I'm not positive that this will fix broken links.

**Comment by sgharms** [comment]
Well, this diff seems to only change the prompting and feedback, so really no objection. I'll merge it now.

**Comment by ollieshmollie** [comment]
@sgharms It also runs the `setup.sh` file I added at the beginning of the `install.sh` script! It's simple enough, but one thing I've learned testing this stuff is that everyone's shell is full of odd quirks. Let me know if there's anything I could do to improve it. 

If you're interested, I'd love to work on a script that installs everything a DBC student would need for the first few weeks with one command (x-code tools, git, rbenv, rspec, et al) while accounting for as many possible variants in their system (i.e. checking if rvm exists and uninstalling). I think it would be a nice intro into week 1 by showing off what bash scripts can accomplish, and provide a more consistent student experience for the weeks ahead.

**Comment by ollieshmollie** [comment]
@sgharms I just discovered a case in point: if a student has been experimenting on their own with rbenv and have it installed, the existing bash profile will prepend the Homebrew path (`/usr/local/bin:/usr/local/sbin:~/bin`) to the front of their path variable. This will incorrectly push the rbenv shims to the middle of their PATH variable. If they also have a version of Ruby installed with Homebrew (which could be likely if they've been playing around), all ruby commands will then default to the Homebrew installed version, no matter how many times they try to use rbenv commands. Not the end of the world, but preventable with a robust environment installation.

**Comment by ollieshmollie** [comment]
@sgharms So of course I fixed all this other stuff, but I might have forgotten to do the _actual_ fix and escape the __git_ps1 variable! Sorry about that. The good news is that once we add that everything should work great. Another inconsistency I was just made aware of today was that some students are either entering the course with an initialized git repo in their home directory, they're accidentally doing it, or something in setup.sh is doing it (highly unlikely, as you checked it yourself and there's no git init's going down). This is also easily preventable when running the install script.

**Pull request merged**
